name: 'C++ Static Analysis'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: codechecker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu_2004:
    name: "Analysis on Ubuntu 20.04"
    runs-on: ubuntu-20.04

    steps:
      # Check YOUR project out!
      - name: "Check out repository"
        uses: actions/checkout@v2
  
      # Prepare a build
      - name: "Prepare build"
        run: |
          mkdir -pv Build
          cd Build
          # cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake ../src -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  
      # Run the analysis
      - uses: whisperity/codechecker-analysis-action@@master
        continue-on-error: true
        id: codechecker
        with:
          llvm-version: 'latest'
          install-custom: true
          version: 'master'
          repository: 'Ericsson/CodeChecker'
  
          config: .github/codechecker.json
  
          logfile: 'Build/compile_commands.json'
  
      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "Full findings"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
          if-no-files-found: error


        
